# Generated by Django 5.1.4 on 2024-12-21 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_user_area_remove_user_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to=settings.AUTH_USER_MODEL),
        ),
    ]
